version: 2.1
jobs:
  build:
    docker:
    - image: cimg/base:2020.01

    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run: make setup
    - run: make login
    - run: make publish
